maker3d/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404
from web.views import Error404View

urlpatterns = [
    path('',include('web.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),
    path('admin/', admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'web.views.Error404View'

web/urls.py
from django.urls import path
from . import views


app_name='web'

urlpatterns = [
    path('',views.index,name='index'),
    path('tienda',views.tienda,name='tienda'),
    path('producto/<int:producto_id>',views.producto,name='producto'),
    path('carrito',views.carrito,name='carrito'),
    path('carrito/add/<int:producto_id>',views.agregar_carrito,name='agregarcarrito'),
    path('carrito/del/<int:producto_id>',views.eliminar_carrito,name='eliminarcarrito'),
    path('carrito/clear',views.limpiar_carrito,name='limpiarcarrito'),
    path('usuario/add',views.crear_usuario,name='crearusuario'),
    path('cuenta',views.cuenta_usuario,name='cuentausuario'),
    path('login',views.login_usuario,name='loginusuario'),
    path('logout',views.logout_usuario,name='logoutusuario'),
    path('cliente/update',views.actualizar_cliente,name='actualizarcliente'),
    path('pedido',views.pedido,name='pedido'),
    path('pedido/add',views.registrar_pedido,name='registrar_pedido'),
    path('paypaltest',views.view_that_asks_for_money,name='paypaltest'),
    path('gracias',views.gracias,name='gracias'),
    path('mis_compras',views.mis_compras,name='mis_compras')
]

web/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tbl_categoria'

    def __str__(self):
        return self.nombre

class Area(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tbl_area'

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    area = models.ForeignKey(Area,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=255,null=True)
    descripcion = models.TextField(null=True)
    detalle = models.TextField(null=True)
    precio = models.DecimalField(max_digits=6,decimal_places=2)
    fecha_registro = models.DateTimeField(auto_now=True)
    size_disponible = models.CharField(max_length=100)
    material = models.CharField(max_length=150)
    tecnologia_fabricada= models.CharField(max_length=255)
    color_disponible=models.CharField(max_length=255)
    musical= models.CharField(max_length=200)
    luces_interno=models.CharField(max_length=200)
    personalizable=models.CharField(max_length=255)
    popularidad = models.DecimalField(max_digits=4,decimal_places=1)
    sku = models.CharField(max_length=10,null=True,unique=True)
    
    class Meta:
        db_table = 'tbl_producto'

    def __str__(self):
        return self.nombre

@receiver(post_save,sender=Producto)
def generar_sku(sender,instance,created,**kwargs):
    if created:
        categoria_cod = instance.categoria.nombre[:2].upper()
        correlativo = str(Producto.objects.count()).zfill(3)
        instance.sku = f'{categoria_cod}{correlativo}'
        instance.save()


class ProductoImagen(models.Model):
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    imagen = models.ImageField(upload_to='galeria',blank=True)
    orden = models.IntegerField(default=1)
    fecha_registro = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tbl_producto_imagen'
        verbose_name_plural = 'Imagenes del Producto'
        verbose_name = 'Imagen del Producto'

    def __str__(self):
        return str(self.imagen)

### modelos para usuarios y cliente ###

from django.contrib.auth.models import User

class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=255)
    dni= models.CharField(max_length=8)
    sexo = models.CharField(max_length=1)
    telefono = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField(null=True)
    direccion = models.TextField()

    class Meta:
        db_table = 'tbl_cliente'

    def __str__(self):
        return self.nombre


##### pedidos #####

class Pedido(models.Model):

    ESTADO_CHOICES = (
        ('0','Solicitado'),
        ('1','Pagado')
    )

    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    fecha_registro = models.DateTimeField(auto_now=True)
    nro_pedido = models.CharField(max_length=20,null=True)
    monto_total = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    estado = models.CharField(max_length=1,default='0',choices=ESTADO_CHOICES)

    class Meta:
        db_table = 'tbl_pedido'

    def __str__(self):
        return self.nro_pedido

class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10,decimal_places=2)

    class Meta:
        db_table = 'tbl_pedido_detalle'

    def __str__(self):
        return self.producto.nombre

web/templates/includes/tienda/filtros.html
{% load static %}
<div class="col-lg-3 col-md-4">
  <!-- Price Start -->
  <h5 class="section-title position-relative text-uppercase mb-3">
    <span class="bg-secondary pr-3">Categorias</span>
  </h5>
  <div class="bg-light p-4 mb-30">
    <form>
      <a
        href="/tienda"
        class="custom-control d-flex align-items-center justify-content-between mb-3"
        ><!--
        <input
          type="checkbox"
          class="custom-control-input"
          checked
          id="price-all"
        />-->
        <label class="" for="price-all">Todas</label>
        <span class="badge border font-weight-normal"><!--{{productos.count}}--></span>
      </a>
      {% for categoria in categorias %}
      <a
        href="/tienda?cat={{categoria.id}}"
        class="custom-control d-flex align-items-center justify-content-between mb-3"
        ><!--
        <input
          type="checkbox"
          class="custom-control-input"
          checked
          id="price-all"
        />-->
        <label class="" for="price-all">{{categoria.nombre}}</label>
        <span class="badge border font-weight-normal"
          >{{categoria.producto_set.all.count}}</span
        >
      </a>
      {% endfor %}
    </form>
  </div>
  <!-- Price End -->

  <!-- Color Start -->
  <h5 class="section-title position-relative text-uppercase mb-3">
    <span class="bg-secondary pr-3">Areas / Tipo</span>
  </h5>
  <div class="bg-light p-4 mb-30">
    <form>
      <a
        href="/tienda"
        class="custom-control d-flex align-items-center justify-content-between mb-3"
        ><!--
        <input
          type="checkbox"
          class="custom-control-input"
          checked
          id="price-all"
        />-->
        <label class="" for="price-all">Todas</label>
        <span class="badge border font-weight-normal"><!--{{productos.count}}--></span>
      </a>
      {% for area in areas %}
      <a
        href="/tienda?are={{area.id}}"
        class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3"
        ><!--
        <input
          type="checkbox"
          class="custom-control-input"
          checked
          id="size-all"
        />-->
        <label class="" for="size-all"
          >{{area.nombre}}</label
        >
        <span class="badge border font-weight-normal"
          >{{area.producto_set.all.count}}</span
        >
      </a>
      {% endfor %}
    </form>
  </div>
  <!-- Color End -->

  <!-- Size Start
    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by size</span></h5>
    <div class="bg-light p-4 mb-30">
        <form>
            <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                <input type="checkbox" class="custom-control-input" checked id="size-all">
                <label class="custom-control-label" for="size-all">All Size</label>
                <span class="badge border font-weight-normal">1000</span>
            </div>
            <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                <input type="checkbox" class="custom-control-input" id="size-1">
                <label class="custom-control-label" for="size-1">XS</label>
                <span class="badge border font-weight-normal">150</span>
            </div>
            <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                <input type="checkbox" class="custom-control-input" id="size-2">
                <label class="custom-control-label" for="size-2">S</label>
                <span class="badge border font-weight-normal">295</span>
            </div>
            <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                <input type="checkbox" class="custom-control-input" id="size-3">
                <label class="custom-control-label" for="size-3">M</label>
                <span class="badge border font-weight-normal">246</span>
            </div>
            <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                <input type="checkbox" class="custom-control-input" id="size-4">
                <label class="custom-control-label" for="size-4">L</label>
                <span class="badge border font-weight-normal">145</span>
            </div>
            <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between">
                <input type="checkbox" class="custom-control-input" id="size-5">
                <label class="custom-control-label" for="size-5">XL</label>
                <span class="badge border font-weight-normal">168</span>
            </div>
        </form>
    </div>
    Size End -->
</div>

web/templates/includes/tienda/producto.html
{% load static %}
<div class="col-lg-9 col-md-8">
  <div class="row pb-3">
    <!--
        <div class="col-12 pb-1">
            <div class="d-flex align-items-center justify-content-between mb-4">
                <div>
                    <button class="btn btn-sm btn-light"><i class="fa fa-th-large"></i></button>
                    <button class="btn btn-sm btn-light ml-2"><i class="fa fa-bars"></i></button>
                </div>
                <div class="ml-2">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">Sorting</button>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="#">Latest</a>
                            <a class="dropdown-item" href="#">Popularity</a>
                            <a class="dropdown-item" href="#">Best Rating</a>
                        </div>
                    </div>
                    <div class="btn-group ml-2">
                        <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">Showing</button>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="#">10</a>
                            <a class="dropdown-item" href="#">20</a>
                            <a class="dropdown-item" href="#">30</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>-->
    {% for producto in productos %}
    <div class="col-lg-4 col-md-6 col-sm-6 pb-1">
      <div class="product-item bg-light mb-4">
        <div class="product-img position-relative overflow-hidden">
          {% if producto.productoimagen_set.exists %}
          <img
            class="img-fluid w-100"
            src="{{producto.productoimagen_set.first.imagen.url}}"
            alt=""
          />
          {% else %}
          <img
            class="img-fluid w-100"
            src="{% static 'img/product-1.jpg' %}"
            alt=""
          />
          {% endif %}
          <div class="product-action">
            <!--
            <a
              class="btn btn-outline-dark btn-square"
              href="/carrito/add/{{producto.id}}"
              ><i class="fa fa-shopping-cart"></i
            ></a>
            
                        <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                        <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-sync-alt"></i></a>-->
            <a
              class="btn btn-outline-dark btn-square"
              href="/producto/{{producto.id}}"
              ><i class="fa fa-search"></i
            ></a>
          </div>
        </div>
        <div class="text-center py-4">
          <a
            class="h6 text-decoration-none text-truncate"
            href="/producto/{{producto.id}}"
            >{{producto.nombre}}</a
          >
          <div class="d-flex align-items-center justify-content-center mt-2">
            <h5>S/.{{producto.precio}}</h5>
            <!--<h6 class="text-muted ml-2"><del>S/.{{producto.precio}}</del></h6>-->
          </div>
          <div class="d-flex align-items-center justify-content-center mb-1">
            <small class="fa fa-star text-primary mr-1"></small>
            <small class="fa fa-star text-primary mr-1"></small>
            <small class="fa fa-star text-primary mr-1"></small>
            <small class="fa fa-star text-primary mr-1"></small>
            <small class="fa fa-star text-primary mr-1"></small>
            <small>{{producto.popularidad}}</small>
          </div>
          <div class="container d-flex justify-content-center">
            <a class="btn btn-outline-dark btn-square" href="/carrito/add/{{producto.id}}"
              ><i class="fa fa-shopping-cart"></i
            ></a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    <!--
        <div class="col-12">
            <nav>
              <ul class="pagination justify-content-center">
                <li class="page-item disabled"><a class="page-link" href="#">Previous</span></a></li>
                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">Next</a></li>
              </ul>
            </nav>
        </div>-->
  </div>
</div>